GCP: Fix the exported requirements.txt file containing unsuitable content
It was including a `-e .` line at the top, which causes this error on deployment:

    ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed with status: FAILURE and message: Obtaining file:///workspace (from -r requirements.txt (line 3))
    ERROR: The editable requirement file:///workspace (from -r requirements.txt (line 3)) cannot be installed when requiring hashes, because there is no single file to hash.