Revert "Try Deno 1.40's new `import.meta.filename`"
This reverts commit 5b8088727c6e1c790a4e573bd2b9eafa97710b56.

Doesn't seem to work on Deno Deploy:

    TypeError: Path must be a string. Received undefined