Deno Deploy: Update todo
It seems like the second parameter for the serve object's fetch(...) method still doesn't exist on Deno Deploy:

    export default {
      fetch(req: Request, info: Deno.ServeHandlerInfo) {
        // ...
        console.warn({
          unhandledUrlRequested: req.url,
          by: (info.remoteAddr as Deno.NetAddr).hostname,
        })
        // ...
      },
    } satisfies Deno.ServeDefaultExport

Results in the following error in Deno Deploy Logs:

    TypeError: Cannot read properties of undefined (reading 'remoteAddr')